#!/bin/bash

echo "🔍 Testing: Logging de Verificación de Campos al Inicio"
echo "====================================================="
echo ""

# Colores para output
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔍 Verificando que el frontend esté actualizado...${NC}"

# Verificar que el frontend se actualizó
FRONTEND_RESPONSE=$(curl -s https://tribus-reservas-app-2024-d989e6f9d084.herokuapp.com/)
if echo "$FRONTEND_RESPONSE" | grep -q "main.6ae23643.js"; then
    echo -e "${GREEN}✅ Frontend actualizado con logging de verificación de campos${NC}"
else
    echo -e "${RED}❌ Frontend no se actualizó correctamente${NC}"
    exit 1
fi

echo ""
echo -e "${BLUE}🔧 Verificando backend...${NC}"
HEALTH_RESPONSE=$(curl -s "https://tribus-backend-api-2024-c417f649c911.herokuapp.com/api/health")
if echo "$HEALTH_RESPONSE" | grep -q "OK"; then
    echo -e "${GREEN}✅ Backend funcionando${NC}"
else
    echo -e "${RED}❌ Backend no disponible${NC}"
    exit 1
fi

echo ""
echo -e "${YELLOW}🔍 Problema Identificado:${NC}"
echo "================================"
echo -e "${RED}❌ Error: 'Todos los campos son requeridos'${NC}"
echo -e "${BLUE}📋 Causa: Datos vacíos enviados al backend${NC}"
echo -e "${BLUE}🎯 Solución: Logging de verificación de campos al inicio${NC}"

echo ""
echo -e "${BLUE}🎯 Instrucciones para Capturar Logs de Verificación:${NC}"
echo "====================================================="
echo "1. Ve a: https://tribus-reservas-app-2024-d989e6f9d084.herokuapp.com"
echo "2. Inicia sesión como admin: admin / admin123"
echo "3. Ve a la sección 'Usuarios'"
echo "4. Haz clic en 'Nuevo Usuario'"
echo "5. Abre las herramientas de desarrollador (F12)"
echo "6. Ve a la pestaña 'Console'"
echo "7. Limpia la consola (Ctrl+L o Cmd+K)"
echo ""
echo -e "${YELLOW}📝 Llena el formulario paso a paso:${NC}"
echo "=========================================="
echo "8. Escribe en 'Nombre': Usuario Test"
echo "   - Debes ver: '📝 Estado actual del formulario: {name: \"Usuario Test\", ...}'"
echo ""
echo "9. Escribe en 'Email': test@example.com"
echo "   - Debes ver: '📝 Estado actual del formulario: {email: \"test@example.com\", ...}'"
echo ""
echo "10. Escribe en 'Username': testuser"
echo "    - Debes ver: '📝 Estado actual del formulario: {username: \"testuser\", ...}'"
echo ""
echo "11. Escribe en 'Contraseña': Test123"
echo "    - Debes ver: '📝 Estado actual del formulario: {password: \"Test123\", ...}'"
echo ""
echo "12. Selecciona 'Rol': Usuario"
echo "    - Debes ver: '📝 Estado actual del formulario: {role: \"user\", ...}'"
echo ""
echo -e "${YELLOW}📝 Haz clic en 'Crear Usuario' y observa los logs:${NC}"
echo "========================================================"
echo "13. Debes ver esta secuencia de logs:"
echo ""
echo -e "${GREEN}✅ Logs que debes ver:${NC}"
echo "   🔘 CLICK: Botón Crear Usuario clickeado"
echo "   🔍 Estado del formulario al hacer clic: {name: \"Usuario Test\", ...}"
echo "   🔍 isFormValid(): true"
echo "   🔍 isLoading: false"
echo "   🚀 INICIO: handleSubmit ejecutándose"
echo "   📝 Estado actual del formulario al inicio: {name: \"Usuario Test\", ...}"
echo "   🔍 Verificación de campos al inicio: {name: \"Usuario Test\", email: \"test@example.com\", ...}"
echo "   🔍 Validación del formulario: {isValid: true, ...}"
echo "   🔍 Verificación final de datos: {name: \"Usuario Test\", ...}"
echo "   📤 Datos que se van a enviar al backend: {...}"
echo "   🔍 Verificación final antes de enviar: {userDataKeys: [...], userDataValues: [...], ...}"
echo "   🔍 ANTES DE ENVIAR AL BACKEND: {userData: {...}, userDataStringified: \"{...}\", ...}"
echo "   🔑 Token de autenticación: Presente"
echo "   🌐 Enviando request a: ..."
echo "   📤 Configuración del request: {...}"
echo "   🔍 BODY DEL REQUEST: {bodyRaw: \"{...}\", bodyParsed: {...}, ...}"
echo "   🔄 Creando usuario en MongoDB Atlas... {...}"
echo "   🔍 Detalle de userData: {name: \"Usuario Test\", ...}"
echo "   🔍 Verificación de campos vacíos: {nameEmpty: false, ...}"

echo ""
echo -e "${RED}❌ Si ves alguno de estos logs, hay un problema:${NC}"
echo "=================================================="
echo "   ❌ NO ves '🔘 CLICK: Botón Crear Usuario clickeado'"
echo "   ❌ NO ves '🚀 INICIO: handleSubmit ejecutándose'"
echo "   ❌ Formulario no válido, deteniendo envío"
echo "   ❌ Error: Datos vacíos detectados antes del envío"
echo "   🔍 Verificación de campos vacíos: {nameEmpty: true, ...}"
echo "   🔑 Token de autenticación: No encontrado"
echo "   🔍 Verificación final antes de enviar: {userDataValues: [\"\", \"\", \"\", \"\", ...]}"
echo "   🔍 ANTES DE ENVIAR AL BACKEND: {userData: {name: \"\", email: \"\", ...}, ...}"
echo "   🔍 BODY DEL REQUEST: {bodyParsed: {name: \"\", email: \"\", ...}, ...}"
echo "   🔍 Verificación de campos al inicio: {name: \"\", email: \"\", ...}"
echo "   🔍 Estado del formulario al hacer clic: {name: \"\", email: \"\", ...}"

echo ""
echo -e "${YELLOW}🔍 Posibles Problemas y Soluciones:${NC}"
echo "============================================="
echo -e "${RED}❌ Si NO ves '🔘 CLICK: Botón Crear Usuario clickeado':${NC}"
echo "   - El botón no está funcionando"
echo "   - El formulario está deshabilitado"
echo "   - Verifica que todos los campos estén llenos"
echo ""
echo -e "${RED}❌ Si ves '🔍 Estado del formulario al hacer clic' con datos vacíos:${NC}"
echo "   - Los datos se están perdiendo antes del clic"
echo "   - Revisa el estado del formulario"
echo ""
echo -e "${RED}❌ Si ves '🔍 isFormValid(): false':${NC}"
echo "   - El formulario no es válido"
echo "   - Verifica que todos los campos estén llenos"
echo ""
echo -e "${RED}❌ Si NO ves '🚀 INICIO: handleSubmit ejecutándose':${NC}"
echo "   - La función handleSubmit no se está ejecutando"
echo "   - Hay un problema con el formulario"
echo "   - Refresca la página (Ctrl+F5)"
echo ""
echo -e "${RED}❌ Si ves '🔍 Verificación de campos al inicio' con datos vacíos:${NC}"
echo "   - Los datos se están perdiendo antes del envío"
echo "   - Revisa el estado del formulario"
echo ""
echo -e "${RED}❌ Si NO ves '📝 Estado actual del formulario':${NC}"
echo "   - El formulario no se está actualizando"
echo "   - Los handlers del formulario no funcionan"
echo "   - Refresca la página (Ctrl+F5)"
echo ""
echo -e "${RED}❌ Si ves '📝 Estado actual del formulario' con datos vacíos:${NC}"
echo "   - Los handlers del formulario no funcionan"
echo "   - Verifica que estés en la versión correcta"
echo ""
echo -e "${RED}❌ Si ves '🔍 ANTES DE ENVIAR AL BACKEND' con datos vacíos:${NC}"
echo "   - Los datos se están perdiendo antes del envío"
echo "   - Revisa el estado del formulario"
echo ""
echo -e "${RED}❌ Si ves '🔍 BODY DEL REQUEST' con datos vacíos:${NC}"
echo "   - Los datos se están perdiendo en el envío"
echo "   - Revisa la configuración del request"
echo ""
echo -e "${RED}❌ Si ves '🔍 Verificación de campos vacíos: {nameEmpty: true, ...}':${NC}"
echo "   - Los datos se están perdiendo antes del envío"
echo "   - Revisa el estado del formulario"
echo ""
echo -e "${RED}❌ Si ves '🔑 Token de autenticación: No encontrado':${NC}"
echo "   - El login no se completó correctamente"
echo "   - Haz logout y vuelve a hacer login"

echo ""
echo -e "${GREEN}🎉 ¡Sistema listo para debugging de verificación de campos!${NC}"
echo ""
echo -e "${YELLOW}💡 Tip: Comparte TODOS los logs de la consola, especialmente:${NC}"
echo "   - Los logs de '🔘 CLICK: Botón Crear Usuario clickeado'"
echo "   - Los logs de '🔍 Estado del formulario al hacer clic'"
echo "   - Los logs de '🔍 isFormValid()'"
echo "   - Los logs de '🔍 isLoading'"
echo "   - Los logs de '🚀 INICIO: handleSubmit ejecutándose'"
echo "   - Los logs de '📝 Estado actual del formulario al inicio'"
echo "   - Los logs de '🔍 Verificación de campos al inicio'"
echo "   - Los logs de '📝 Estado actual del formulario'"
echo "   - Los logs de '🔍 Verificación final antes de enviar'"
echo "   - Los logs de '🔍 ANTES DE ENVIAR AL BACKEND'"
echo "   - Los logs de '🔍 BODY DEL REQUEST'"
echo "   - Los logs de '🔍 Verificación de campos vacíos'"
echo "   - Los logs de '🔍 Detalle de userData'"
echo ""
echo -e "${BLUE}🎯 Objetivo: Identificar exactamente dónde se pierden los datos${NC}"
echo ""
